/*--- Commandes de drop table ---*/

DROP TABLE IF EXISTS Personnel CASCADE;
DROP TABLE IF EXISTS Client CASCADE;
DROP TABLE IF EXISTS Magasin CASCADE;
DROP TABLE IF EXISTS ComposantE CASCADE;
DROP TABLE IF EXISTS Achat CASCADE;
DROP TABLE IF EXISTS travailler CASCADE;
DROP TABLE IF EXISTS accederInfo CASCADE;
DROP TABLE IF EXISTS vendre CASCADE;
DROP TABLE IF EXISTS acheter CASCADE;
DROP TABLE IF EXISTS provenance CASCADE;
DROP TABLE IF EXISTS DateEntite CASCADE;